
CREATE TABLE [dbo].[DB_MAN_CATALOG](
	[ID_DB_MAN_CATALOG] [int] IDENTITY(1,1) NOT NULL,
	[DB_MAN_CATALOG_OBJET] [varchar](100) NOT NULL,
	[DB_MAN_CATALOG_EXPLAIN] [varchar](max) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


