TRUNCATE TABLE [dbo].[DB_MAN_CATALOG]
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_ADD_CONFIG', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_ConvertTableToHtml_include', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_Gen_AuditLevel', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_SHOW_NOTIF', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_TEMPLATE_MAIL', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_Create_BAK', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_WriteStringToFile', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DBA_MAN_LOG', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_Get_List_Backup', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_DBCC_CHECK', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_Check_login', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_CREATE_SINGLE_JOB', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_DROP_JOBS', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_RecoverDeletedRecord', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_Ftp_GetDir', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_DatabaseIntegrityCheck', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_IndexOptimize', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_CommandExecute', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_BCK_OBJ', 'Without Explain')
INSERT INTO [dbo].[DB_MAN_CATALOG] ([DB_MAN_CATALOG_OBJET], [DB_MAN_CATALOG_EXPLAIN]) VALUES ('DB_MAN_Convert_Query_To_Insert', 'Without Explain')

declare @temp varchar(1000)
SELECT  name  FROM dbo.sysobjects WHERE (type = 'P')


 select @TEMP 

 
 drop table #TempTableForConvert
 SELECT  name AS [DB_MAN_CATALOG_OBJET],'Without Explain' AS DB_MAN_CATALOG_EXPLAIN INTO #TempTableForConvert FROM dbo.sysobjects WHERE (type = 'P')
EXEC dbo.[DB_MAN_Convert_Query_To_Insert] '#TempTableForConvert', '[dbo].[DB_MAN_CATALOG]'


